// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeq6Tzp-CblQZglipj7fycDSN5QF6e5do',
    appId: '1:811793546212:web:31ea2de069cba705e025f1',
    messagingSenderId: '811793546212',
    projectId: 'homeserva-fcm',
    authDomain: 'homeserva-fcm.firebaseapp.com',
    storageBucket: 'homeserva-fcm.appspot.com',
    measurementId: 'G-FTP7DKQ3Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn-5nV36tOR5-IkAAMFi6LVq41fcygISY',
    appId: '1:811793546212:android:729278d948aadb08e025f1',
    messagingSenderId: '811793546212',
    projectId: 'homeserva-fcm',
    storageBucket: 'homeserva-fcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLqAiGML41ILe6xEbzogvX7bxNr5iFPFY',
    appId: '1:811793546212:ios:b2ebb9ed05483621e025f1',
    messagingSenderId: '811793546212',
    projectId: 'homeserva-fcm',
    storageBucket: 'homeserva-fcm.appspot.com',
    iosClientId:
        '811793546212-cv0af31vmrj10kft75f8mujrk91htrrb.apps.googleusercontent.com',
    iosBundleId: 'com.homeserva.homeserva2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLqAiGML41ILe6xEbzogvX7bxNr5iFPFY',
    appId: '1:811793546212:ios:b2ebb9ed05483621e025f1',
    messagingSenderId: '811793546212',
    projectId: 'homeserva-fcm',
    storageBucket: 'homeserva-fcm.appspot.com',
    iosClientId:
        '811793546212-cv0af31vmrj10kft75f8mujrk91htrrb.apps.googleusercontent.com',
    iosBundleId: 'com.homeserva.homeserva2',
  );
}
